using System;
using UnityEngine;

namespace HanziDefend.View
{
    /// <summary>
    /// Runtime-safe catalog generated by the editor art pipeline. Game code only asks for
    /// semantic keys; replacing an imported sprite never requires a code or scene change.
    /// </summary>
    [CreateAssetMenu(menuName = "HanziDefend/Battle Art Catalog", fileName = "HanziDefendArtCatalog")]
    public sealed class BattleArtCatalog : ScriptableObject
    {
        [Serializable]
        public sealed class Entry
        {
            public string Key = string.Empty;
            public Sprite Sprite;
        }

        public Entry[] Entries = Array.Empty<Entry>();

        public Sprite Find(string key)
        {
            if (string.IsNullOrEmpty(key) || Entries == null)
            {
                return null;
            }

            for (var index = 0; index < Entries.Length; index++)
            {
                var entry = Entries[index];
                if (entry != null && string.Equals(entry.Key, key, StringComparison.Ordinal))
                {
                    return entry.Sprite;
                }
            }

            return null;
        }
    }

    public interface IBattleArtSource
    {
        Sprite Find(string key);
    }

    public sealed class ResourcesBattleArtSource : IBattleArtSource
    {
        private const string CatalogResourceName = "HanziDefendArtCatalog";
        private readonly BattleArtCatalog catalog;

        public ResourcesBattleArtSource()
            : this(Resources.Load<BattleArtCatalog>(CatalogResourceName))
        {
        }

        public ResourcesBattleArtSource(BattleArtCatalog catalog)
        {
            this.catalog = catalog;
        }

        public Sprite Find(string key)
        {
            return catalog == null ? null : catalog.Find(key);
        }
    }
}
